use crate::ir::{Function, Stmt, Operand};
use crate::dataflow::{ResolvedCall, ResolvedArg, StructPattern};
use std::collections::{HashMap, HashSet};

pub struct Emitter {
    output: String,
    indent: usize,
}

impl Emitter {
    pub fn new() -> Self {
        Emitter { output: String::new(), indent: 0 }
    }

    fn emit_line(&mut self, line: &str) {
        let indent = "    ".repeat(self.indent);
        self.output.push_str(&indent);
        self.output.push_str(line);
        self.output.push('\n');
    }

    fn emit_blank(&mut self) {
        self.output.push('\n');
    }

    pub fn emit_header_comment(&mut self, binary_path: &str, func_count: usize, import_count: usize) {
        self.emit_line("/*");
        self.emit_line(&format!(" * Reconstructed from: {}", binary_path));
        self.emit_line(&format!(" * Functions lifted: {}", func_count));
        self.emit_line(&format!(" * Imports resolved: {}", import_count));
        self.emit_line(" *");
        self.emit_line(" * This code was generated by static dataflow analysis.");
        self.emit_line(" * It reflects the actual call sequences, data flow, and control");
        self.emit_line(" * flow extracted from the binary's instructions.");
        self.emit_line(" * It is NOT a template or heuristic output.");
        self.emit_line(" */");
        self.emit_blank();
        self.emit_line("#include <stdio.h>");
        self.emit_line("#include <stdlib.h>");
        self.emit_line("#include <string.h>");
        self.emit_line("#include <stdint.h>");
        self.emit_blank();
    }


    pub fn emit_struct_types(&mut self, patterns: &[StructPattern]) {
        for (i, pat) in patterns.iter().enumerate() {
            let origin = pat.origin_call.as_deref().unwrap_or("unknown");
            self.emit_line(&format!("/* Struct inferred from base v{} (allocated by {}) */", pat.base_var, origin));
            self.emit_line(&format!("typedef struct {{"));
            self.indent += 1;

            let mut prev_offset: i64 = 0;
            for &off in &pat.offsets {
                if off < 0 { continue; }
                let padding = off - prev_offset;
                if padding > 0 && padding < off {
                    self.emit_line(&format!("uint8_t _pad_{}[{}];", prev_offset, padding));
                }
                self.emit_line(&format!("uint64_t field_{:#x};  /* offset {} */", off, off));
                prev_offset = off + 8;
            }

            self.indent -= 1;
            self.emit_line(&format!("}} struct_{}_t;  /* from {} */", i, origin));
            self.emit_blank();
        }
    }

    pub fn emit_function(
        &mut self,
        func: &Function,
        resolved_calls: &[ResolvedCall],
        struct_patterns: &[StructPattern],
    ) {
        let mut calls_by_block: HashMap<usize, Vec<&ResolvedCall>> = HashMap::new();
        for rc in resolved_calls {
            calls_by_block.entry(rc.block_id).or_default().push(rc);
        }

        let back_edge_targets: HashSet<usize> = func.blocks.iter()
            .flat_map(|bb| bb.succs.iter().filter(|&&s| s <= bb.id).copied())
            .collect();

        self.emit_line(&format!("void {}() {{", func.name));
        self.indent += 1;

 
        let mut named_vars: HashMap<String, String> = HashMap::new();
        for rc in resolved_calls {
            let var_name = call_result_name(&rc.target);
            if !named_vars.contains_key(&rc.target) {
                self.emit_line(&format!("void* {}; /* result of {} */", var_name, rc.target));
                named_vars.insert(rc.target.clone(), var_name);
            }
        }
        if !resolved_calls.is_empty() { self.emit_blank(); }

        for bb in &func.blocks {
            if back_edge_targets.contains(&bb.id) {
                self.emit_blank();
                self.emit_line(&format!("/* loop header */"));
            }

            self.emit_line(&format!("bb_{}:", bb.id));
            self.indent += 1;
            if let Some(calls) = calls_by_block.get(&bb.id) {
                for rc in calls {
                    self.emit_resolved_call(rc, &named_vars);
                }
            }

            if let Some(terminal) = bb.stmts.iter().rev().find(|s| {
                matches!(s, Stmt::Branch{..} | Stmt::Jump(_) | Stmt::Return(_))
            }) {
                self.emit_terminal(terminal);
            }

            self.indent -= 1;
        }

        self.indent -= 1;
        self.emit_line("}");
        self.emit_blank();
    }

    fn emit_resolved_call(&mut self, rc: &ResolvedCall, named_vars: &HashMap<String, String>) {
        let arg_strs: Vec<String> = rc.args.iter().enumerate().map(|(i, arg)| {
            match arg {
                ResolvedArg::Const(0) => "NULL".to_string(),
                ResolvedArg::Const(n) => format!("{}", n),
                ResolvedArg::StringLiteral(s) => format!("\"{}\"", s.replace('"', "\\\"")),
                ResolvedArg::CallResult(callee) => {
                    named_vars.get(callee).cloned().unwrap_or_else(|| format!("result_{}", callee))
                }
                ResolvedArg::FieldLoad { base_call, offset } => {
                    let base = named_vars.get(base_call).cloned().unwrap_or_else(|| format!("ptr_{}", base_call));
                    format!("((struct*){})->field_{:#x}", base, offset)
                }
                ResolvedArg::Unknown(desc) => format!("/* {} */ ???", desc),
            }
        }).collect();

        let var_name = named_vars.get(&rc.target);
        let call_str = format!("{}({});", rc.target, arg_strs.join(", "));
        match var_name {
            Some(name) => self.emit_line(&format!("{} = {}", name, call_str)),
            None       => self.emit_line(&call_str),
        }
    }

    fn emit_terminal(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Branch { cond, true_bb, false_bb } => {
                let cond_str = format_condition(cond);
                self.emit_line(&format!("if ({}) goto bb_{}; else goto bb_{};", cond_str, true_bb, false_bb));
            }
            Stmt::Jump(target) => {
                self.emit_line(&format!("goto bb_{};", target));
            }
            Stmt::Return(Some(v)) => {
                self.emit_line(&format!("return; /* return value: {} */", v));
            }
            Stmt::Return(None) => {
                self.emit_line("return;");
            }
            _ => {}
        }
    }

    pub fn finish(self) -> String {
        self.output
    }
}

fn call_result_name(target: &str) -> String {
    let base = target
        .trim_start_matches('_')
        .replace(['@', '.', ':', '-'], "_");
    match base.as_str() {
        "malloc" | "calloc" | "realloc" => "buf".to_string(),
        "fopen"  => "fp".to_string(),
        "socket" => "sock_fd".to_string(),
        "accept" => "client_fd".to_string(),
        "open"   => "fd".to_string(),
        other    => format!("{}_result", other),
    }
}

fn format_condition(op: &Operand) -> String {
    match op {
        Operand::Symbol(s, _) => {
            if s.starts_with("eq(")  { s.replace("eq(",  "").replace(')', "").replace(", ", " == ") }
            else if s.starts_with("ne(")  { s.replace("ne(",  "").replace(')', "").replace(", ", " != ") }
            else if s.starts_with("lt_s(") { s.replace("lt_s(", "").replace(')', "").replace(", ", " < ") }
            else if s.starts_with("le_s(") { s.replace("le_s(", "").replace(')', "").replace(", ", " <= ") }
            else if s.starts_with("gt_s(") { s.replace("gt_s(", "").replace(')', "").replace(", ", " > ") }
            else if s.starts_with("ge_s(") { s.replace("ge_s(", "").replace(')', "").replace(", ", " >= ") }
            else { s.clone() }
        }
        Operand::Const(1) => "1 /* unresolved condition */".to_string(),
        Operand::Var(v)   => format!("{}", v),
        other             => format!("{}", other),
    }
}
